# Generated by Django 4.0.3 on 2023-12-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecks',
            name='check_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paychecks',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
